# Makefile, Author: Robert Bergeron

WARN = -Wall -Wextra -Werror -Wpedantic -Wshadow
# full gcc exec command
C = gcc -g -O0 -std=c11
CWARN = ${C} ${WARN} -fdiagnostics-color=never
CYY = ${C} -Wno-sign-compare
CDEP = gcc -std=c11 -MM ${WARN}
MKFILE = Makefile
DEPFILE = ${MKFILE}.dep
GMAKE = ${MAKE} --no-print-directory
# name of the compiled executable
EXECNAME = bompiler
# name of the testing executable
TSTEXECNAME = test
# main source file
MAIN = main.c
# test source file
TEST = test.c
# .c source files
SRC = map.c string_set.c lyutils.c astree.c vector.c
# .h header files
HDR = map.h string_set.h vector.h lyutils.h auxlib.h astree.h symtable.h
# .o object files
OBJ = ${SRC:.c=.o} ${GENSRC:.c=.o}
# .gch header somethings?
GCH = ${HDR:=.gch}
# files generated by flex and bison
GENSRC = yylex.c yyparse.c
GENHDR = yyparse.h
# files generated by the formatter
FMT = ${SRC:=~} ${HDR:=~} ${TEST:=~}

all : ${DEPFILE} ${EXECNAME}

${EXECNAME} : ${OBJ}
	${C} -o bompiler ${OBJ}

${TSTEXECNAME} : ${OBJ} ${TEST:.c=.o}
	${C} -o test ${OBJ} ${TEST:.c=.o}

yylex.o : yylex.c
	${CYY} -c $< ${HDR} ${GENHDR}

yyparse.o : yyparse.c yyparse.h
	${CYY} -c $< ${HDR} ${GENHDR}

%.o : %.c ${GENHDR}
	${C} -c $< ${HDR} ${GENHDR}

yylex.c : scanner.l
	flex --outfile=yylex.c scanner.l

yyparse.c yyparse.h : parser.y
	bison -Wall -v --defines=yyparse.h --output=yyparse.c parser.y

clean:
	rm -f ${OBJ} ${TEST:.c=.o} ${MAIN:.c=.o} ${GENSRC} ${GENHDR} ${DEPFILE} \
	${GCH}

spotless: clean
	rm -f ${EXECNAME} ${TSTEXECNAME} ${FMT}

ci: 
	git add ${HDR} ${SRC} ${MKFILE} ${TEST} README.md DESIGN.md .gitignore \
	parser.y scanner.l

deps: ${SRC} ${GEN}
	${CDEP} ${SRC} ${GEN} ${MKFILE} >> ${DEPFILE}

format:
	indent -l80 -nfca -hnl -ncdb -bad -bap -nbc -bbo -nbfda -npsl -br -brs \
	-brf -ce -cdw -lps -saf -sai -saw -pcs -cs -bs -nut -ts4 -i4 -pi4 -ci4 \
	-cli4 -ppi4 -cbi0 -bli0 parser.y ${SRC} ${HDR} ${TEST}

${DEPFILE} :
	@ touch ${DEPFILE}
	${GMAKE} deps
