# Makefile, Author: Robert Bergeron

WARN = -Wall -Wextra -Werror -Wpedantic -Wshadow
# full gcc exec command
C = gcc -g -O0 -std=c11
CWARN = ${C} ${WARN} -fdiagnostics-color=never
CYY = ${C} -Wno-sign-compare -Wno-register
CDEP = gcc -std=c11 -MM ${WARN}
MKFILE = Makefile
DEPFILE = ${MKFILE}.dep
GMAKE = ${MAKE} --no-print-directory
# name of the compiled executable
EXECNAME = bompiler
# name of the testing executable
TSTEXECNAME = test
# main source file
MAIN = main.c
# test source file
TEST = test.c
# .c source files
SRC = map.c string_set.c
# .h header files
HDR = map.h string_set.h
# .o object files
OBJ = ${SRC:.c=.o}
# .gch header somethings?
GCH = ${HDR}.gch
# files generated by flex and bison
GENSRC = yylex.c yyparse.c
GENHDR = yyparse.h
# files generated by the formatter
FMT = ${SRC}~ ${HDR}~ ${TEST}~

all : ${DEPFILE} ${EXECNAME}

${EXECNAME} : ${OBJ}
	${C} -o bompiler ${OBJ}

${TSTEXECNAME} : ${OBJ} ${TEST:.c=.o}
	${C} -o test ${OBJ} ${TEST:.c=.o}

%.o : %.c
	${C} -c $< ${HDR}

clean:
	rm -f ${OBJ} ${TEST:.c=.o} ${MAIN:.c=.o} ${GENSRC} ${GENHDR} ${DEPFILE}\
		${GCH}

spotless: clean
	rm -f ${EXECNAME} ${TSTEXECNAME} ${FMT}

ci: 
	git add ${HDR} ${SRC} ${MKFILE} ${TEST} README.md DESIGN.md .gitignore

deps: ${SRC} ${GEN}
	${CDEP} ${SRC} ${GEN} ${MKFILE} >> ${DEPFILE}

format:
	indent -l80 -nfca -hnl -ncdb -bad -bap -nbc -bbo -nbfda -npsl -br -brs \
	-brf -ce -cdw -lps -saf -sai -saw -pcs -cs -bs -nut -ts4 -i4 -pi4 -ci4 \
	-cli4 -ppi4 -cbi0 -bli0 ${SRC} ${HDR} ${TEST}

${DEPFILE} :
	@ touch ${DEPFILE}
	${GMAKE} deps
